import { incident001 } from './src/scenarios/incident-001.js?v=20260911-15';
import { Simulator } from './src/engine.js?v=20260911-15';
import { scoreRun } from './src/scoring.js?v=20260911-14';
import { runDiagnosticCommand } from './src/terminal.js?v=20260911-15';

const scenario = incident001;
const state = new Simulator(scenario);
const root = document.querySelector('#app');
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let mayaOpen = false;
let mayaMessages = [];

function reset(){ state.reset(); mayaOpen=false; mayaMessages=[]; }
function progress(){ const p={intro:0,investigate:20,evidence:40,diagnose:60,action:75,reasoning:88,results:100}[state.stage] ?? 0; return `<div class="progress"><div style="width:${p}%"></div></div>`; }
function map(){
  const checked=new Set(state.checks); const selected=state.hypothesis;
  const nodeState=id => selected===id ? 'selected' : checked.has(id) ? (id==='firewall' ? 'fault' : 'healthy') : 'unknown';
  const nodes=scenario.visualMap.nodes;
  const nodeHtml=id=>{const n=nodes.find(x=>x[0]===id);const status=nodeState(id);const label=status==='unknown'?'Not checked':status==='fault'?'Problem found':status==='selected'?'Your hypothesis':'Checked';return `<div class="map-node ${status}" title="${esc(n[3])}"><div class="map-icon">${n[1]}</div><div><strong>${esc(n[2])}</strong><span>${label}</span></div></div>`;};
  return `<div class="engineering-map"><div class="map-head"><div><div class="eyebrow">System view</div><strong>${esc(scenario.visualMap.title)}</strong><p>${esc(scenario.visualMap.subtitle)}</p></div><div class="map-legend"><span><i class="dot unknown"></i>Unknown</span><span><i class="dot healthy"></i>Checked</span><span><i class="dot fault"></i>Issue</span></div></div><div class="map-flow">${nodeHtml('user')}<div class="map-arrow">↓</div>${nodeHtml('dns')}<div class="map-arrow">↓</div>${nodeHtml('firewall')}<div class="map-arrow">↓</div>${nodeHtml('web')}<div class="map-arrow">↓</div>${nodeHtml('db')}</div></div>`;
}
function terminal(){
  const history=state.terminal.history;
  const lines=history.length?history.map(item=>`<div class="terminal-entry"><div class="terminal-command"><span>engineer@prod:~$</span> ${esc(item.input)}</div><pre class="terminal-output ${item.ok?'':'terminal-error'}">${esc(item.output)}</pre></div>`).join(''):'<div class="terminal-empty">No commands yet. Start with a diagnostic question, not a guess.</div>';
  return `<div class="diagnostic-console"><div class="console-head"><div><div class="eyebrow">Diagnostic Console</div><strong>${esc(scenario.terminal.title)}</strong><p>${esc(scenario.terminal.prompt)}</p></div><div class="console-badge">SIMULATED</div></div><div class="terminal-window"><div class="terminal-history">${lines}</div><form class="terminal-form" data-terminal-form><span>engineer@prod:~$</span><input id="terminal-input" autocomplete="off" spellcheck="false" placeholder="Type a command…" aria-label="Diagnostic terminal command"><button class="terminal-run" type="submit">Run</button></form></div><div class="terminal-coach">💡 Try to obtain evidence. For example, you might investigate DNS with <code>nslookup portal.company.com</code>.</div>${state.checks.length?`<button class="secondary console-review" data-diagnose="1">Review evidence (${state.checks.length} check${state.checks.length>1?'s':''}) →</button>`:''}</div>`;
}
function contextualMaya(){
  if(state.stage==='investigate') return 'Where would you start? Don’t worry about being right immediately — show me how you would investigate.';
  if(state.stage==='evidence') return state.checks.length<2?'Good. Keep collecting evidence before committing to a cause. What else can you verify?':'Now compare the evidence. Which component is actually showing abnormal behavior?';
  if(state.stage==='diagnose') return 'Choose the hypothesis that best explains the evidence — not just the symptom.';
  if(state.stage==='action') return 'What action would restore service based on your diagnosis?';
  if(state.stage==='reasoning') return 'Connect the timeline, evidence, root cause and action. English, Tamil, Tanglish or mixed language is fine.';
  if(state.stage==='results') return 'Now look at what you did well and where your engineering reasoning can become stronger.';
  return 'I’m Maya. I won’t give you the answer first. I’ll help you reason your way to it.';
}
function mayaReply(text){
  const t=text.toLowerCase();
  if(t.includes('hint')||t.includes('help')) return 'Start with evidence, not a conclusion. Think about the path a user request takes before it reaches the application.';
  if(t.includes('database')||t.includes('db')) return 'What evidence would make you suspect the database? If the database is healthy, what does that allow you to rule out?';
  if(t.includes('dns')) return 'Good hypothesis to test. What can you learn about DNS resolution before deciding it is the cause?';
  if(t.includes('firewall')) return 'That is worth investigating. Look for evidence about incoming traffic and recent configuration changes.';
  if(t.includes('web server')||t.includes('server')) return 'Check whether the server is actually unhealthy. CPU, memory, process status and application health can help you distinguish a server problem from an upstream problem.';
  return 'Tell me what you observed and what you are considering next. I’ll help you test the reasoning without giving away the answer.';
}
function maya(){
  const messages=mayaMessages.map(m=>`<div class="maya-message ${m.role}">${esc(m.text)}</div>`).join('');
  if(!mayaOpen)return `<div class="maya-widget"><button class="maya-fab" data-maya-toggle aria-label="Open Maya"><img src="src/maya/avatar.svg" alt=""><span class="maya-online"></span></button><div class="maya-label">Ask Maya</div></div>`;
  return `<div class="maya-widget open"><div class="maya-panel"><div class="maya-panel-head"><div class="maya-identity"><img class="maya-avatar" src="src/maya/avatar.svg" alt="Maya"><div><strong>Maya</strong><span>Engineering Mentor · Online</span></div></div><button class="maya-close" data-maya-toggle aria-label="Minimize Maya">×</button></div><div class="maya-chat"><div class="maya-message maya-intro">${esc(contextualMaya())}</div>${messages}</div><form class="maya-form" data-maya-form><input id="maya-input" autocomplete="off" placeholder="Ask Maya…" aria-label="Message Maya"><button type="submit" aria-label="Send message">↑</button></form><div class="maya-foot">Maya guides your reasoning — she won’t solve the incident for you.</div></div></div>`;
}
function shell(content,withMap=false){ root.innerHTML=progress()+`<section class="card">${withMap?map():''}${content}</section>${maya()}`; }
function back(label,stage){ return `<button class="secondary" data-back="${stage}">← ${label}</button>`; }

function feedback(){
  const r=scoreRun(scenario,state), diagnosisCorrect=state.hypothesis===scenario.correctHypothesis, actionCorrect=state.action===scenario.correctAction, firewallChecked=state.checks.includes('firewall'), webChecked=state.checks.includes('web'), dbChecked=state.checks.includes('db'), reasoning=state.reasoning.trim();
  const reasoningSignals=['firewall','https','443','block','blocked','traffic','09:10','web server','database','healthy'].filter(x=>reasoning.toLowerCase().includes(x)); const items=[];
  if(diagnosisCorrect)items.push(`<div class="feedback good"><strong>✓ Diagnosis was correct.</strong><span>You identified the firewall as the component blocking the user's HTTPS request.</span></div>`);else items.push(`<div class="feedback improve"><strong>✗ Diagnosis: ${esc(state.hypothesis||'not selected')}</strong><span>The evidence showed DNS was resolving, the web server was running, and the database was healthy. The abnormal evidence was the disabled <code>ALLOW-HTTPS-PROD</code> rule blocking TCP/443.</span></div>`);
  if(actionCorrect)items.push(`<div class="feedback good"><strong>✓ Remediation was correct.</strong><span>Re-enabling <code>ALLOW-HTTPS-PROD</code> addresses the actual failure: incoming HTTPS traffic was being blocked.</span></div>`);else items.push(`<div class="feedback improve"><strong>✗ Remediation would not fix the incident.</strong><span>${state.action?`You chose “${esc(state.action)}”.`:'No remediation was selected.'} That does not address the disabled firewall rule blocking TCP/443. The appropriate action is to re-enable <code>ALLOW-HTTPS-PROD</code>, then verify external HTTPS access.</span></div>`);
  if(firewallChecked)items.push(`<div class="feedback good"><strong>✓ You found the key evidence.</strong><span>The firewall audit showed a 09:10 configuration change, the HTTPS rule disabled, and incoming TCP/443 blocked. This is the strongest evidence in the incident.</span></div>`);else items.push(`<div class="feedback improve"><strong>→ Missing the decisive evidence.</strong><span>You did not inspect the firewall. The decisive clue was the disabled <code>ALLOW-HTTPS-PROD</code> rule blocking incoming TCP/443.</span></div>`);
  if(!webChecked||!dbChecked){const missing=[];if(!webChecked)missing.push('web server');if(!dbChecked)missing.push('database');items.push(`<div class="feedback tip"><strong>→ Strengthen your investigation.</strong><span>You could have checked the ${missing.join(' and ')} to rule out other plausible causes before deciding. A strong engineer compares alternatives rather than jumping to the first explanation.</span></div>`);}
  if(reasoningSignals.length>=4)items.push(`<div class="feedback good"><strong>✓ Your explanation contained useful technical evidence.</strong><span>You connected several relevant signals from the incident. Keep making the evidence → cause → action chain explicit.</span></div>`);else items.push(`<div class="feedback improve"><strong>→ Your reasoning needs more evidence-to-cause connection.</strong><span>Explain <em>what you observed</em>, <em>why it points to the root cause</em>, and <em>why your chosen action fixes that cause</em>.</span></div>`);
  if(state.hints>0)items.push(`<div class="feedback tip"><strong>💡 You used ${state.hints} Maya hint${state.hints>1?'s':''}.</strong><span>Hints are available when you are stuck, but try to gather and compare evidence independently before asking Maya next time.</span></div>`);
  return {r,items};
}

function render(){
  if(state.stage==='intro')return shell(`<div class="eyebrow">${esc(scenario.subject)} · ${esc(scenario.difficulty)}</div><h1 class="title">${esc(scenario.title)}</h1><p class="sub">${esc(scenario.intro)}</p><div class="meta">${scenario.skills.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}<span class="tag">${esc(scenario.time)}</span></div><div class="row"><button class="primary" data-start="1">Start investigation</button><button class="secondary" data-seminar="1">Seminar mode</button></div>`);
  if(state.stage==='investigate')return shell(`<div class="eyebrow">Step 1 · Investigate${state.seminar?' · Seminar mode':''}</div><h2>Investigate before you decide.</h2><p class="sub">Use the map to understand the request path. You can inspect a component directly or use the diagnostic console to gather evidence.</p>${terminal()}<div class="investigation-divider"><span>Or inspect a component directly</span></div><div class="actions">${scenario.investigation.map(x=>`<button class="choice" data-check="${esc(x[0])}"><strong>${esc(x[1])}</strong><span>${esc(x[2])}</span></button>`).join('')}</div>`,true);
  if(state.stage==='evidence')return shell(`<div class="eyebrow">Step 2 · Gather evidence</div><h2>What did you find?</h2><p class="sub">The map updates as you investigate. Use the evidence to eliminate possible causes.</p>${state.checks.map(id=>`<div class="evidence"><h3>${esc(scenario.evidence[id][0])}</h3><pre>${esc(scenario.evidence[id][1])}</pre></div>`).join('')}${state.terminal.history.length?`<div class="terminal-notes"><strong>Diagnostic console activity</strong><span>${state.terminal.commandsUsed.length} recognised command${state.terminal.commandsUsed.length===1?'':'s'} used. Your terminal evidence remains part of this investigation.</span></div>`:''}<div class="actions">${scenario.investigation.filter(x=>!state.checks.includes(x[0])).map(x=>`<button class="choice" data-check="${esc(x[0])}"><strong>${esc(x[1])}</strong><span>${esc(x[2])}</span></button>`).join('')}<button class="primary" data-diagnose="1">I’m ready to form a hypothesis</button>${back('Back to investigation','investigate')}</div>`,true);
  if(state.stage==='diagnose')return shell(`<div class="eyebrow">Step 3 · Diagnose</div><h2>What is the most likely cause?</h2><p class="sub">Use the map and evidence together. Choose the explanation that best fits what you found.</p><div class="actions">${scenario.hypotheses.map(x=>`<button class="choice" data-hypothesis="${esc(x[0])}"><strong>${esc(x[1])}</strong></button>`).join('')}${back('Back to evidence','evidence')}</div>`,true);
  if(state.stage==='action')return shell(`<div class="eyebrow">Step 4 · Restore</div><h2>What would you do?</h2><p class="sub">Select the action that should restore service.</p><div class="actions">${scenario.actions.map(x=>`<button class="choice" data-fix="${esc(x[0])}"><strong>${esc(x[1])}</strong></button>`).join('')}${back('Back to diagnosis','diagnose')}</div>`);
  if(state.stage==='reasoning')return shell(`<div class="eyebrow">Step 5 · Explain your reasoning</div><h2>Explain it in your own language.</h2><p class="sub">Tell Maya what you found, why you think it caused the problem, and why your chosen action will fix it.</p><div style="margin-top:18px"><div style="font-size:13px;font-weight:750;margin-bottom:8px">Choose your language</div><div class="row"><button class="${state.language==='en-IN'?'primary':'secondary'}" data-language="en-IN">🇬🇧 English</button><button class="${state.language==='ta-IN'?'primary':'secondary'}" data-language="ta-IN">தமிழ்</button></div><p style="font-size:12px;color:#6b7280;margin:10px 0 0">Your language does not affect your engineering score.</p></div><textarea id="reasoning" placeholder="${state.language==='ta-IN'?'உங்கள் முடிவை தமிழில் விளக்குங்கள்...':'Example: 09:10 firewall rule was disabled, so HTTPS traffic on port 443 was blocked...'}">${esc(state.reasoning)}</textarea><div class="row" style="margin-top:12px"><button class="primary" data-submit="1">Submit reasoning</button><button class="secondary" data-voice="1">🎙 Speak your answer</button><button class="secondary" data-hint="1">Ask Maya for a hint</button></div><p id="voice-status" style="font-size:12px;color:#6b7280;margin:10px 0 0;min-height:18px"></p>${state.hints?`<p class="hint">Hint: ${esc(scenario.hints[state.hints-1])}</p>`:''}${back('Back to action','action')}`);
  const {r,items}=feedback(); const summary=r.score>=85?'Strong engineering investigation.':r.score>=70?'Good start. Now strengthen the evidence-to-reasoning connection.':'Keep investigating. Focus on ruling out alternatives before deciding.';
  return shell(`<div class="eyebrow">Incident complete</div><h2>Investigation complete.</h2><div class="score">${r.score}<small>/100</small></div><p class="sub" style="margin-top:8px"><strong>${summary}</strong></p><div class="success">Root cause: HTTPS traffic was blocked by the firewall.</div><div style="margin-top:22px"><div class="metric"><span>Investigation</span><strong>${r.investigation}/25</strong></div><div class="metric"><span>Evidence usage</span><strong>${r.evidence}/20</strong></div><div class="metric"><span>Technical reasoning</span><strong>${r.reasoning}/30</strong></div><div class="metric"><span>Decision</span><strong>${r.decision}/15</strong></div><div class="metric"><span>Explanation</span><strong>${r.explanation}/10</strong></div>${r.hintPenalty?`<div class="metric"><span>Maya hint penalty</span><strong>-${r.hintPenalty}</strong></div>`:''}</div><div style="margin-top:26px"><div class="eyebrow">What went wrong?</div><h2 style="margin-top:8px">Learn from your investigation</h2><p class="sub">Instead of only telling you that something needs improvement, Maya explains exactly what the evidence showed and what you could do differently.</p>${items.join('')}</div><div style="margin-top:28px"><button class="primary" data-restart="1">Run the incident again</button></div>`);
}

function speak(text,lang){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang||'en-IN';u.rate=.96;speechSynthesis.speak(u);}
function setVoiceStatus(message,kind='info'){const el=document.querySelector('#voice-status');if(!el)return;el.textContent=message;el.style.color=kind==='error'?'#b42318':kind==='good'?'#087443':'#6b7280';}
function listen(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setVoiceStatus('Voice input is not available in this browser. Please use Chrome or Edge for voice input.','error');return;}const r=new SR();r.lang=state.language||'en-IN';r.interimResults=false;r.continuous=false;r.maxAlternatives=1;const b=document.querySelector('[data-voice]');if(b)b.textContent='🎙 Listening…';setVoiceStatus('Listening…');r.onresult=e=>{const el=document.querySelector('#reasoning');const transcript=e.results?.[0]?.[0]?.transcript||'';if(el&&transcript)el.value=transcript;setVoiceStatus('Voice captured. You can edit your answer before submitting.','good');};r.onerror=e=>{setVoiceStatus(e.error==='not-allowed'?'Microphone access was blocked. Allow microphone access for this site and try again.':`Voice input could not start (${e.error||'unknown error'}). Try again.`,'error');if(b)b.textContent='🎙 Speak your answer';};r.onend=()=>{const x=document.querySelector('[data-voice]');if(x)x.textContent='🎙 Speak your answer';};try{r.start();}catch(err){setVoiceStatus('Voice input could not start. Please try again.','error');}}

root.addEventListener('submit',e=>{if(e.target.matches('[data-terminal-form]')){e.preventDefault();const input=e.target.querySelector('#terminal-input');const raw=input?.value||'';if(!raw.trim())return;runDiagnosticCommand(scenario,state,raw);render();requestAnimationFrame(()=>document.querySelector('#terminal-input')?.focus());return;}if(e.target.matches('[data-maya-form]')){e.preventDefault();const input=e.target.querySelector('#maya-input');const text=input?.value?.trim()||'';if(!text)return;mayaMessages.push({role:'student',text});mayaMessages.push({role:'maya',text:mayaReply(text)});render();requestAnimationFrame(()=>document.querySelector('#maya-input')?.focus());}});
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mayaToggle!==undefined){mayaOpen=!mayaOpen;render();requestAnimationFrame(()=>document.querySelector('#maya-input')?.focus());return;}if(b.hasAttribute('data-start')){reset();state.start();render();return;}if(b.hasAttribute('data-seminar')){reset();state.seminar=true;state.start();render();return;}if(b.dataset.check){state.investigate(b.dataset.check);render();return;}if(b.hasAttribute('data-diagnose')){state.stage='diagnose';render();return;}if(b.dataset.hypothesis){state.chooseHypothesis(b.dataset.hypothesis);render();return;}if(b.dataset.fix){state.chooseAction(b.dataset.fix);render();return;}if(b.hasAttribute('data-hint')){state.askHint();render();return;}if(b.hasAttribute('data-voice')){listen();return;}if(b.dataset.language){state.language=b.dataset.language;render();return;}if(b.dataset.speak){speak(b.dataset.speak,state.language);return;}if(b.hasAttribute('data-submit')){state.submitReasoning(document.querySelector('#reasoning')?.value||'');render();return;}if(b.hasAttribute('data-restart')){reset();render();return;}if(b.dataset.back){state.stage=b.dataset.back;render();}});
render();
