import {scenario} from './scenario.js';
import {Simulator} from './engine.js';
import {scoreRun} from './scoring.js';
import {mayaMessage} from './maya.js';

const sim=new Simulator(scenario); const root=document.querySelector('#app'); let hintText=''; let seminar=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function progress(){const map={intro:0,investigate:20,evidence:40,decision:65,reasoning:82,learning:92,results:100};return `<div class="progress"><div style="width:${map[sim.stage]}%"></div></div>`}
function speak(text){if(!('speechSynthesis' in window))return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.rate=.96; speechSynthesis.speak(u)}
function listen(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Voice input is supported in Chrome or Edge.');return} const r=new SR();r.lang='en-IN';r.interimResults=false;r.onresult=e=>{document.querySelector('#reasoning').value=e.results[0][0].transcript};r.start()}
function maya(){const msg=mayaMessage(sim.stage,sim,scenario);return `<div class="maya"><img class="maya-avatar" src="src/maya/avatar.svg" alt="Maya"><div class="maya-copy"><div class="maya-name">Maya · Engineering Mentor</div><div class="maya-text">${esc(msg)}</div>${hintText?`<div class="hint">Hint ${sim.hints}/${scenario.hints.length}: ${esc(hintText)}</div>`:''}<button class="speak" data-speak="${esc(msg)}">🔊 Hear Maya</button></div></div>`}
function shell(content){root.innerHTML=`${progress()}<section class="card">${content}${maya()}</section>`}
function render(){
 if(sim.stage==='intro') return shell(`<div class="eyebrow">Production incident · ${scenario.difficulty}</div><h1 class="title">${scenario.title}</h1><p class="sub">${scenario.intro}</p><div class="meta">${scenario.skills.map(x=>`<span class="tag">${x}</span>`).join('')}<span class="tag">${scenario.time}</span></div><div class="row"><button class="primary" data-start>Start investigation</button><button class="secondary" data-seminar>Seminar mode</button></div>`);
 if(sim.stage==='investigate') return shell(`<div class="eyebrow">Step 1 · Investigate ${seminar?'· Seminar mode':''}</div><h2>Where do you start?</h2><p class="sub">Pick one check. There is no penalty for an imperfect first move — the important thing is how you investigate.</p><div class="actions">${scenario.investigation.map(x=>`<button class="choice" data-investigate="${x.id}"><strong>${x.label}</strong><span>${x.detail}</span></button>`).join('')}</div>`);
 if(sim.stage==='evidence') return shell(`<div class="eyebrow">Step 2 · Gather evidence</div><h2>What did you find?</h2><p class="sub">Review the result, then choose another investigation. Build the picture before you diagnose.</p>${sim.investigations.map(id=>{const e=scenario.evidence[id];return `<div class="evidence"><h3>${e.title}</h3><pre>${esc(e.text)}</pre></div>`}).join('')}<div class="actions">${scenario.investigation.filter(x=>!sim.investigations.includes(x.id)).map(x=>`<button class="choice" data-investigate="${x.id}"><strong>${x.label}</strong><span>${x.detail}</span></button>`).join('')}<button class="primary" data-diagnose>I'm ready to form a hypothesis</button></div>`);
 if(sim.stage==='decision') return shell(`<div class="eyebrow">Step 3 · Diagnose</div><h2>What is the most likely cause?</h2><p class="sub">Choose the explanation that best fits the evidence you collected.</p><div class="actions">${scenario.hypotheses.map(x=>`<button class="choice" data-hypothesis="${x.id}"><strong>${x.label}</strong></button>`).join('')}</div>`);
 if(sim.stage==='reasoning') return shell(`<div class="eyebrow">Step 4 · Restore & explain</div><h2>What would you do?</h2><p class="sub">Select the action, then explain your reasoning in your own words. English, Tamil, Tanglish, or mixed language is fine.</p><div class="actions">${scenario.actions.map(x=>`<button class="choice" data-action="${x.id}"><strong>${x.label}</strong></button>`).join('')}</div>`);
 if(sim.stage==='learning') return shell(`<div class="eyebrow">Step 5 · Explain your reasoning</div><h2>Tell Maya what happened.</h2><p class="sub">Connect the timeline, evidence, root cause, and action. Don't worry about perfect English.</p><textarea id="reasoning" placeholder="Example: 09:10 firewall rule disable aayirukku..."></textarea><div class="row" style="margin-top:12px"><button class="primary" data-submit>Submit reasoning</button><button class="secondary" data-hint>Ask Maya for a hint</button><button class="secondary" data-voice>🎙 Voice input</button></div>`);
 const r=scoreRun(scenario,sim); return shell(`<div class="eyebrow">Incident complete</div><h2>Good investigation.</h2><div class="score">${r.score}<small>/100</small></div><div class="success">Root cause: HTTPS traffic was blocked by the firewall.</div><div style="margin-top:22px">${[['Investigation',r.investigation],['Evidence usage',r.evidence],['Technical reasoning',r.reasoning],['Decision making',r.decision],['Explanation',r.explanation]].map(([k,v])=>`<div class="metric"><span>${k}</span><strong>${v}</strong></div>`).join('')} ${r.hintPenalty?`<div class="metric"><span>Maya hint penalty</span><strong>-${r.hintPenalty}</strong></div>`:''}</div><h3 style="margin-top:26px">Learning check</h3><ol>${scenario.learning.map(q=>`<li style="margin:10px 0">${q}</li>`).join('')}</ol><button class="primary" data-restart style="margin-top:18px">Run the incident again</button>`);
}
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.start){sim.start();render()}else if(b.dataset.seminar){seminar=true;sim.start();render()}else if(b.dataset.investigate){sim.investigate(b.dataset.investigate);render()}else if(b.dataset.diagnose){sim.stage='decision';render()}else if(b.dataset.hypothesis){sim.chooseHypothesis(b.dataset.hypothesis);render()}else if(b.dataset.action){sim.chooseAction(b.dataset.action);render()}else if(b.dataset.hint){hintText=sim.askHint();render()}else if(b.dataset.voice){listen()}else if(b.dataset.speak){speak(b.dataset.speak)}else if(b.dataset.submit){sim.submitReasoning(document.querySelector('#reasoning').value);render()}else if(b.dataset.restart){sim.reset();hintText='';seminar=false;render()}});
render();
